### PR TITLE
Support "customView" property on Annotation

### PR DESCRIPTION
**Pull request by hansemannn**
Addressing #86. Please check the notes regarding the sizing before, thx!

### CODE REVIEW

**Comment by hansemannn** [comment]
@yozef to review :-) Travis only fails because the generated `$(TI_MODULE_VERSION)` compiler flag is added to 6.1.0, which isn't used in the CI, yet.

**Comment by DouglasHennrich** [comment]
Can you provide the module of this PR ? so I can use it until it be merged =)

**Comment by yozef** [comment]
Finally was able to compile with SDK 6.1.0.GA and CLI 6.2.2
Tested customView successfully.
2017-05-30 at 9 08 23 am

**Comment by hansemannn** [comment]
Thanks man! Still wondering if `infoWindow` may do the same already, I did not validate that bth.

**Comment by yozef** [comment]
let me check...

**Comment by yozef** [comment]
InfoWindow = the Bubble that appears over the icon/customView -- works as expected
customView = to be used in lieu of an Image icon (the annotation icon itself)

Also, the click event on infoWindow shows appropriately:
```
{"clicksource":"infoWindow","annotation":{"userData":{"uuid":"35A8BA6E-7789-4B6A-A971-605AFE7FAF90"},"title":"Hello Custom View","latitude":45.368122,"longitude":-73.913653,"subtitle":null},....
```

**Comment by DouglasHennrich** [comment]
How can I change it's center so it put the customView center on the pin's "footer" ?

As you can see, my pin footer is on the extreme bottom of my customView

simulator screen shot 30 de mai de 2017 10 54 17

**Comment by yozef** [comment]
I think these should do it on Annotation:
```
groundOffset: {
        x: 0.5,
        y: 0,5
    },
```

**Pull request merged**
